export default () => ({
  COOKIE_SECRET: process.env.COOKIE_SECRET,
  MESSENGER_APP_ID: process.env.MESSENGER_APP_ID,
  MESSENGER_APP_SECRET: process.env.MESSENGER_APP_SECRET,
  MESSENGER_EXTENSIONS_URL: process.env.MESSENGER_EXTENSIONS_URL,
  MESSENGER_PAGE_ID: process.env.MESSENGER_PAGE_ID,
  PORT: process.env.PORT || 8080,
  SENTRY_DSN: process.env.SENTRY_DSN,
});
